<?php

// Auto-generated by scripts/build-peers.php — do not edit manually.
// Re-run when content structure changes.
// Override specific entries with $meta['peers'] in the content file.

return [
    '/about' => [
        'es' => NULL,
    ],
    '/blog' => [
        'es' => '/es/blog',
    ],
    '/en' => [
        'es' => '/es',
    ],
    '/es' => [
        'en' => '/en',
    ],
    '/es/acerca' => [
        'en' => NULL,
    ],
    '/es/blog' => [
        'en' => '/blog',
    ],
    '/es/caracteristicas' => [
        'en' => NULL,
    ],
    '/es/caracteristicas/arquitectura-archivos' => [
        'en' => NULL,
    ],
    '/es/caracteristicas/ciclo-solicitudes' => [
        'en' => NULL,
    ],
    '/es/caracteristicas/enrutamiento-archivos' => [
        'en' => NULL,
    ],
    '/es/caracteristicas/internacionalizacion' => [
        'en' => NULL,
    ],
    '/es/caracteristicas/nucleo-aplicacion' => [
        'en' => NULL,
    ],
    '/es/caracteristicas/repositorio-contenido' => [
        'en' => NULL,
    ],
    '/es/caracteristicas/sistema-plantillas' => [
        'en' => NULL,
    ],
    '/features' => [
        'es' => NULL,
    ],
    '/features/application-kernel' => [
        'es' => NULL,
    ],
    '/features/content-repository' => [
        'es' => NULL,
    ],
    '/features/file-based-routing' => [
        'es' => NULL,
    ],
    '/features/filesystem-architecture' => [
        'es' => NULL,
    ],
    '/features/internationalization' => [
        'es' => NULL,
    ],
    '/features/request-lifecycle' => [
        'es' => NULL,
    ],
    '/features/template-system' => [
        'es' => NULL,
    ],
];
