<?php

declare(strict_types=1);

/**
 * DEPRECATED — no longer needed.
 *
 * Peer resolution is now computed at runtime by PeerMap based on matching
 * relative slugs across locale directories. No pre-build step required.
 *
 * Override peers for a specific page via $meta['peers'] in the content file:
 *   $meta = ['peers' => ['es' => '/es/acerca']];
 *
 * This file is kept for reference only and can be deleted.
 */

$base = dirname(__DIR__);
require $base . '/bootstrap/autoload.php';

$config        = \Wordless\Config\Config::load(require $base . '/config.php');
$contentDir    = $config->get('content_dir');
$locales       = $config->get('locales', ['en']);
$defaultLocale = $config->get('default_locale', 'en');

$map = [];

foreach ($locales as $locale) {
    $localeDir = $contentDir . DIRECTORY_SEPARATOR . $locale;

    if (!is_dir($localeDir)) {
        echo "Skipping missing locale directory: {$localeDir}\n";
        continue;
    }

    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($localeDir, FilesystemIterator::SKIP_DOTS)
    );

    foreach ($iterator as $file) {
        if ($file->getExtension() !== 'php') {
            continue;
        }

        // Relative path within the locale dir, normalised to forward slashes
        $relative = str_replace(
            '\\',
            '/',
            ltrim(str_replace($localeDir, '', $file->getPathname()), DIRECTORY_SEPARATOR)
        );

        // Canonical URL for this file.
        // Prepend slash so that "/index.php" replacement works for nested index files.
        // A bare "index.php" at the locale root maps to "/{locale}", not "/{locale}/index".
        if ($relative === 'index.php') {
            $slug = '';
        } else {
            $slug = trim(str_replace(['/index.php', '.php'], ['', ''], '/' . $relative), '/');
        }

        // Locale root (slug = '') always keeps the locale prefix so the splash at / stays separate.
        if ($slug === '') {
            $canonical = '/' . $locale;
        } elseif ($locale === $defaultLocale) {
            $canonical = '/' . $slug;
        } else {
            $canonical = '/' . $locale . '/' . $slug;
        }

        $peers = [];
        foreach ($locales as $otherLocale) {
            if ($otherLocale === $locale) {
                continue;
            }
            $otherFile = $contentDir . DIRECTORY_SEPARATOR . $otherLocale . DIRECTORY_SEPARATOR . $relative;
            if (file_exists($otherFile)) {
                if ($relative === 'index.php') {
                    $otherSlug = '';
                } else {
                    $otherSlug = trim(str_replace(['/index.php', '.php'], ['', ''], '/' . $relative), '/');
                }
                if ($otherSlug === '') {
                    $peers[$otherLocale] = '/' . $otherLocale;
                } elseif ($otherLocale === $defaultLocale) {
                    $peers[$otherLocale] = '/' . $otherSlug;
                } else {
                    $peers[$otherLocale] = '/' . $otherLocale . '/' . $otherSlug;
                }
            } else {
                $peers[$otherLocale] = null;
            }
        }

        $map[$canonical] = $peers;
    }
}

ksort($map);

$lines = [
    '<?php',
    '',
    '// Auto-generated by scripts/build-peers.php — do not edit manually.',
    '// Re-run when content structure changes.',
    '// Override specific entries with $meta[\'peers\'] in the content file.',
    '',
    'return [',
];

foreach ($map as $canonical => $peers) {
    $lines[] = '    ' . var_export($canonical, true) . ' => [';
    foreach ($peers as $locale => $peerPath) {
        $lines[] = '        ' . var_export($locale, true) . ' => ' . var_export($peerPath, true) . ',';
    }
    $lines[] = '    ],';
}

$lines[] = '];';
$lines[] = '';

$dest = $base . '/storage/peers.php';
file_put_contents($dest, implode("\n", $lines));

echo "Written: {$dest}\n";
echo 'Mapped ' . count($map) . " canonical paths.\n";
